Group 11 case study 1
rilling/robocodeFall2024 pull request #6
Opened 2024-10-14 16:56 UTC by YajingLiu2357

Fix the technical debt under the folder robocode.battle

Fix the following technical debt:
- The diamond operator(<>) should be used
- Class variable field should not have public accessibility
- Generic exceptions should never be thrown
- Non-thread-safe fields should not be static
- @Deprecated code should not be used 
- “Switch” statements should have default clauses
- Conditionally executed code should be reachable
- Subclasses that add fields should override equals
- Merge this if statement with the enclosing one.
- Extract nested code blocks into smaller methods.
- Change multiple "try" blocks to a try-with-resources
- Add the "@Override" annotation above this method signature
- Declare "y" and all following declarations on a separate line
- Make "dateFormat" an instance variable
- Cast one of the operands of this division operation to a "double".

2024-10-14 17:56 UTC, 0matleb2 requested changes

2024-10-14 17:56 UTC, 0matleb2 commented on robocode.battle/src/main/java/net/sf/robocode/battle/peer/RobotPeer.java
> -				} // if the robot hits 2 walls at the same time (rare, but just in case)
Are you sure this block is unreachable? Looks like could be reachable. Also the comment was left behind.

2024-10-14 17:56 UTC, 0matleb2 commented on robocode.battle/src/main/java/net/sf/robocode/battle/peer/TeamPeer.java
> +		if (! super.equals(obj)){
Whitespace in this method is not matching the conventions in the project.

2024-10-14 17:57 UTC, 0matleb2 commented
A lot more than 1 technical debt fix per group member here. 😅

2024-10-14 18:11 UTC, YajingLiu2357 commented on robocode.battle/src/main/java/net/sf/robocode/battle/peer/RobotPeer.java
> -				} // if the robot hits 2 walls at the same time (rare, but just in case)
Thank you for your comment! SonarQube analyzes this condition as always true. Do I need to use another condition or change it back? Thank you for your help!
<img width="1512" alt="373844162-9b972bbf-3164-4096-9e9f-741acd466e5a" src="https://github.com/user-attachments/assets/b791a639-da2c-4700-8f8b-0fd50ef3705b">

2024-10-15 02:39 UTC, 0matleb2 commented on robocode.battle/src/main/java/net/sf/robocode/battle/peer/RobotPeer.java
> -				} // if the robot hits 2 walls at the same time (rare, but just in case)
SonarQube is not always correct. It'll use heuristics to detect **_potential_** issues like this, though there's a chance it might be a false positive. It's up to us as developers to analyze this code as determine if it is a real issue or a false positive. This is a thorny and difficult to understand conditional, I think it might warrant a closer look to be sure this refactoring is safe.

2024-10-15 02:41 UTC, 0matleb2 commented
> @0matleb2 Sorry for any inconvenience we cause. The requirement document requires that each member need to finish at least one issue so we misunderstand that we do not have an upper limit for the number of issues. Do we need to change some issues back to reduce the number of issues we fix? Thank you!

No, it's OK as is. The only trouble with fixing a lot of issues in one PR is it becomes difficult to review, and has a higher chance of causing merge conflicts.

2024-10-15 04:12 UTC, YajingLiu2357 commented on robocode.battle/src/main/java/net/sf/robocode/battle/peer/RobotPeer.java
> -				} // if the robot hits 2 walls at the same time (rare, but just in case)
Got it! Thank you! After checking, I am still unsure whether this refactoring is safe. I decide to revert the changes to prevent introducing new bugs to the system.

2024-10-15 04:31 UTC, YajingLiu2357 commented
Got it! Thank you! We will prevent fixing a lot of issues in one PR next time. I have changed my codes based on your suggestions. Could you check it again? Thank you for your work!

2024-10-15 13:59 UTC, 0matleb2 commented on robocode.battle/src/main/java/net/sf/robocode/battle/peer/RobotPeer.java
> -				} // if the robot hits 2 walls at the same time (rare, but just in case)
I took a closer look at this code. The execution branches where `adjustY` can be set to a non-zero value are mutually exclusive with the branches that set `adjustX` to a non-zero value. This means that if `adjustX` is non-zero, then `adjustY` must be zero, and SonarQube is correct. The effect is that the 2 conditional branches following `adjustY == 0` are unreachable. The fix would be to remove the 2 unreachable branches, and change the `adjustY == 0` else if branch to an else. I suggest either try that fix or revert the change.

2024-10-15 21:01 UTC, Beavan1997 commented
Hi @0matleb2 

@YajingLiu2357 made the changes as requested and has merged it in her main. Could you please review and approve this PR to merge with the Professor's branch.

Thank you

2024-10-16 01:14 UTC, 0matleb2 approved these changes
Thanks for the changes. LGTM!

2024-10-16 01:16 UTC, merged